version: '3.8'

services:
  django:

    build:
      context: .
      dockerfile: ./DockerFiles/Django/Dockerfile
      
    image: django

    env_file:
      - ./.envs/.django
      - ./.envs/.postgres

    volumes:
      - .:/app

    ports:
      - 8000:8000

    depends_on:
      - db
    command: /bin/sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"


  db:
    build:
      context: .
      dockerfile: ./DockerFiles/Postgres/Dockerfile
    image: db

    restart: always
  